### PR TITLE
Split sync version to new module

### PR DESCRIPTION
**Pull request by yumauri**
This is continue of https://github.com/lessmess-dev/effector-localstorage/pull/13 :)

But if you are OK with latest state, maybe this PR is overkill, because now there are two almost identical files, needed to support...

But on the other hand I reduced size of main version to 99 B ^_^

### CODE REVIEW

**Comment by yumauri** [comment]
I've removed support for `sessionStorage`, because package called `effector-localstorage`, and with `.onChange` functionality sessionStorage doesn't make sense

**Comment by yumauri** [comment]
By the way, while thinking about API, I came up with slightly different approach, and published new package [effector-storage](https://github.com/yumauri/effector-storage), which is heavily inspired by this package, but in my opinion API is more ... _natural_.

I didn't dare changing API here, maybe there are already plenty of dependant packages...

**Comment by ilyalesik** [comment]
Thanks! `effector-storage` looks great, can you make PR with it into [awesome-effector](https://github.com/ilyalesik/awesome-effector) list?

**Comment by yumauri** [comment]
Done [PR#1](https://github.com/ilyalesik/awesome-effector/pull/1)

**Pull request merged**
