### PR TITLE
Reduce size / Add support of sessionStorage

### PR DESCRIPTION
**Pull request by yumauri**
I felt guilty for increased size :)
So I decreased it to 111 B + added support for sessionStorage as bonus, should work like this:
```javascript
const counterSessionStorage = connectLocalStorage("counter", window.sessionStorage)
```

### CODE REVIEW

**Comment by yumauri** [comment]
It is possible to reduce size even more, using `storage[key]` instead of get/setItem, but I decided this is way too dangerous...

**Comment by ilyalesik** [comment]
That's awesome, thanks! I published v0.3.1.

**Comment by ilyalesik** [comment]
@all-contributors please add @yumauri  for code

**Comment by yumauri** [comment]
@ilyalesik wow, thank you! Does that mean I can push/review/merge PRs here? I've never been assigned as contributor before (aside from my business/work account), so this is kinda new for me :)

**Comment by yumauri** [comment]
Or this is just acknowledgment? :)

**Comment by ilyalesik** [comment]
That's just acknowledgment, but I also add you as a maintainer with push/review/merge PR permissions at the repo settings. 🙂

**Comment by yumauri** [comment]
Much appreciated! 😘
I think today I'll make one more PR, it will definitely increase size again, and, maybe, a bit controversial, so I will not merge it without discussion.

**Pull request merged**
